//Login
export const VALIDATE_CREDENTIALS = 'VALIDATE_CREDENTIALS';
export const FETCH_USERS = 'FETCH_USERS';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const DETAIL_USER = 'DETAIL_USER';
export const LOGOUT_USER = 'LOGOUT_USER';


//MedicalAppointments
export const FETCH_MEDICALS= 'FETCH_MEDICALS';
export const ERROR_EXIST= 'ERROR_EXIST';
export const CREATE_MEDICAL_APPOINTMENT= 'CREATE_MEDICAL_APPOINTMENT';
export const UNMOUNT_MEDICALS= 'UNMOUNT_MEDICALS';
export const CANCEL_MEDICAL_APPOINTMENT= 'CANCEL_MEDICAL_APPOINTMENT';
export const ERROR_CANCEL_MEDICAL_APPOINTMENT= 'ERROR_CANCEL_MEDICAL_APPOINTMENT';